// seeds/03_properties.js
export const seed = async (knex) => {
  await knex("properties").del();

  await knex("properties").insert([
    // 0–10
    {
      position: 0,
      name: "Go",
      type: "special",
      color: null,
      price: null,
      mortgage_value: null,
      rent: null,
      development_cost: null,
    },
    {
      position: 1,
      name: "Mediterranean Avenue",
      type: "street",
      color: "brown",
      price: 60,
      mortgage_value: 30,
      rent: JSON.stringify({
        site: 2,
        one_house: 10,
        two_houses: 30,
        three_houses: 90,
        four_houses: 160,
        hotel: 250,
      }),
      development_cost: JSON.stringify({ house: 50, hotel: 50 }),
    },
    {
      position: 2,
      name: "Community Chest",
      type: "community_chest",
      color: null,
    },
    {
      position: 3,
      name: "Baltic Avenue",
      type: "street",
      color: "brown",
      price: 60,
      mortgage_value: 30,
      rent: JSON.stringify({
        site: 4,
        one_house: 20,
        two_houses: 60,
        three_houses: 180,
        four_houses: 320,
        hotel: 450,
      }),
      development_cost: JSON.stringify({ house: 50, hotel: 50 }),
    },
    {
      position: 4,
      name: "Income Tax",
      type: "tax",
      color: null,
      rent: JSON.stringify({ flat: 200 }),
    },
    {
      position: 5,
      name: "Reading Railroad",
      type: "railroad",
      price: 200,
      mortgage_value: 100,
      rent: JSON.stringify({ 1: 25, 2: 50, 3: 100, 4: 200 }),
    },
    {
      position: 6,
      name: "Oriental Avenue",
      type: "street",
      color: "light_blue",
      price: 100,
      mortgage_value: 50,
      rent: JSON.stringify({
        site: 6,
        one_house: 30,
        two_houses: 90,
        three_houses: 270,
        four_houses: 400,
        hotel: 550,
      }),
      development_cost: JSON.stringify({ house: 50, hotel: 50 }),
    },
    { position: 7, name: "Chance", type: "chance" },
    {
      position: 8,
      name: "Vermont Avenue",
      type: "street",
      color: "light_blue",
      price: 100,
      mortgage_value: 50,
      rent: JSON.stringify({
        site: 6,
        one_house: 30,
        two_houses: 90,
        three_houses: 270,
        four_houses: 400,
        hotel: 550,
      }),
      development_cost: JSON.stringify({ house: 50, hotel: 50 }),
    },
    {
      position: 9,
      name: "Connecticut Avenue",
      type: "street",
      color: "light_blue",
      price: 120,
      mortgage_value: 60,
      rent: JSON.stringify({
        site: 8,
        one_house: 40,
        two_houses: 100,
        three_houses: 300,
        four_houses: 450,
        hotel: 600,
      }),
      development_cost: JSON.stringify({ house: 50, hotel: 50 }),
    },
    { position: 10, name: "Jail / Just Visiting", type: "special" },

    // 11–20
    {
      position: 11,
      name: "St. Charles Place",
      type: "street",
      color: "pink",
      price: 140,
      mortgage_value: 70,
      rent: JSON.stringify({
        site: 10,
        one_house: 50,
        two_houses: 150,
        three_houses: 450,
        four_houses: 625,
        hotel: 750,
      }),
      development_cost: JSON.stringify({ house: 100, hotel: 100 }),
    },
    {
      position: 12,
      name: "Electric Company",
      type: "utility",
      price: 150,
      mortgage_value: 75,
      rent: JSON.stringify({ dice_x4: true, dice_x10: true }),
    },
    {
      position: 13,
      name: "States Avenue",
      type: "street",
      color: "pink",
      price: 140,
      mortgage_value: 70,
      rent: JSON.stringify({
        site: 10,
        one_house: 50,
        two_houses: 150,
        three_houses: 450,
        four_houses: 625,
        hotel: 750,
      }),
      development_cost: JSON.stringify({ house: 100, hotel: 100 }),
    },
    {
      position: 14,
      name: "Virginia Avenue",
      type: "street",
      color: "pink",
      price: 160,
      mortgage_value: 80,
      rent: JSON.stringify({
        site: 12,
        one_house: 60,
        two_houses: 180,
        three_houses: 500,
        four_houses: 700,
        hotel: 900,
      }),
      development_cost: JSON.stringify({ house: 100, hotel: 100 }),
    },
    {
      position: 15,
      name: "Pennsylvania Railroad",
      type: "railroad",
      price: 200,
      mortgage_value: 100,
      rent: JSON.stringify({ 1: 25, 2: 50, 3: 100, 4: 200 }),
    },
    {
      position: 16,
      name: "St. James Place",
      type: "street",
      color: "orange",
      price: 180,
      mortgage_value: 90,
      rent: JSON.stringify({
        site: 14,
        one_house: 70,
        two_houses: 200,
        three_houses: 550,
        four_houses: 750,
        hotel: 950,
      }),
      development_cost: JSON.stringify({ house: 100, hotel: 100 }),
    },
    { position: 17, name: "Community Chest", type: "community_chest" },
    {
      position: 18,
      name: "Tennessee Avenue",
      type: "street",
      color: "orange",
      price: 180,
      mortgage_value: 90,
      rent: JSON.stringify({
        site: 14,
        one_house: 70,
        two_houses: 200,
        three_houses: 550,
        four_houses: 750,
        hotel: 950,
      }),
      development_cost: JSON.stringify({ house: 100, hotel: 100 }),
    },
    {
      position: 19,
      name: "New York Avenue",
      type: "street",
      color: "orange",
      price: 200,
      mortgage_value: 100,
      rent: JSON.stringify({
        site: 16,
        one_house: 80,
        two_houses: 220,
        three_houses: 600,
        four_houses: 800,
        hotel: 1000,
      }),
      development_cost: JSON.stringify({ house: 100, hotel: 100 }),
    },
    { position: 20, name: "Free Parking", type: "special" },

    // 21–30
    {
      position: 21,
      name: "Kentucky Avenue",
      type: "street",
      color: "red",
      price: 220,
      mortgage_value: 110,
      rent: JSON.stringify({
        site: 18,
        one_house: 90,
        two_houses: 250,
        three_houses: 700,
        four_houses: 875,
        hotel: 1050,
      }),
      development_cost: JSON.stringify({ house: 150, hotel: 150 }),
    },
    { position: 22, name: "Chance", type: "chance" },
    {
      position: 23,
      name: "Indiana Avenue",
      type: "street",
      color: "red",
      price: 220,
      mortgage_value: 110,
      rent: JSON.stringify({
        site: 18,
        one_house: 90,
        two_houses: 250,
        three_houses: 700,
        four_houses: 875,
        hotel: 1050,
      }),
      development_cost: JSON.stringify({ house: 150, hotel: 150 }),
    },
    {
      position: 24,
      name: "Illinois Avenue",
      type: "street",
      color: "red",
      price: 240,
      mortgage_value: 120,
      rent: JSON.stringify({
        site: 20,
        one_house: 100,
        two_houses: 300,
        three_houses: 750,
        four_houses: 925,
        hotel: 1100,
      }),
      development_cost: JSON.stringify({ house: 150, hotel: 150 }),
    },
    {
      position: 25,
      name: "B&O Railroad",
      type: "railroad",
      price: 200,
      mortgage_value: 100,
      rent: JSON.stringify({ 1: 25, 2: 50, 3: 100, 4: 200 }),
    },
    {
      position: 26,
      name: "Atlantic Avenue",
      type: "street",
      color: "yellow",
      price: 260,
      mortgage_value: 130,
      rent: JSON.stringify({
        site: 22,
        one_house: 110,
        two_houses: 330,
        three_houses: 800,
        four_houses: 975,
        hotel: 1150,
      }),
      development_cost: JSON.stringify({ house: 150, hotel: 150 }),
    },
    {
      position: 27,
      name: "Ventnor Avenue",
      type: "street",
      color: "yellow",
      price: 260,
      mortgage_value: 130,
      rent: JSON.stringify({
        site: 22,
        one_house: 110,
        two_houses: 330,
        three_houses: 800,
        four_houses: 975,
        hotel: 1150,
      }),
      development_cost: JSON.stringify({ house: 150, hotel: 150 }),
    },
    {
      position: 28,
      name: "Water Works",
      type: "utility",
      price: 150,
      mortgage_value: 75,
      rent: JSON.stringify({ dice_x4: true, dice_x10: true }),
    },
    {
      position: 29,
      name: "Marvin Gardens",
      type: "street",
      color: "yellow",
      price: 280,
      mortgage_value: 140,
      rent: JSON.stringify({
        site: 24,
        one_house: 120,
        two_houses: 360,
        three_houses: 850,
        four_houses: 1025,
        hotel: 1200,
      }),
      development_cost: JSON.stringify({ house: 150, hotel: 150 }),
    },
    { position: 30, name: "Go to Jail", type: "special" },

    // 31–39
    {
      position: 31,
      name: "Pacific Avenue",
      type: "street",
      color: "green",
      price: 300,
      mortgage_value: 150,
      rent: JSON.stringify({
        site: 26,
        one_house: 130,
        two_houses: 390,
        three_houses: 900,
        four_houses: 1100,
        hotel: 1275,
      }),
      development_cost: JSON.stringify({ house: 200, hotel: 200 }),
    },
    {
      position: 32,
      name: "North Carolina Avenue",
      type: "street",
      color: "green",
      price: 300,
      mortgage_value: 150,
      rent: JSON.stringify({
        site: 26,
        one_house: 130,
        two_houses: 390,
        three_houses: 900,
        four_houses: 1100,
        hotel: 1275,
      }),
      development_cost: JSON.stringify({ house: 200, hotel: 200 }),
    },
    { position: 33, name: "Community Chest", type: "community_chest" },
    {
      position: 34,
      name: "Pennsylvania Avenue",
      type: "street",
      color: "green",
      price: 320,
      mortgage_value: 160,
      rent: JSON.stringify({
        site: 28,
        one_house: 150,
        two_houses: 450,
        three_houses: 1000,
        four_houses: 1200,
        hotel: 1400,
      }),
      development_cost: JSON.stringify({ house: 200, hotel: 200 }),
    },
    {
      position: 35,
      name: "Short Line",
      type: "railroad",
      price: 200,
      mortgage_value: 100,
      rent: JSON.stringify({ 1: 25, 2: 50, 3: 100, 4: 200 }),
    },
    { position: 36, name: "Chance", type: "chance" },
    {
      position: 37,
      name: "Park Place",
      type: "street",
      color: "dark_blue",
      price: 350,
      mortgage_value: 175,
      rent: JSON.stringify({
        site: 35,
        one_house: 175,
        two_houses: 500,
        three_houses: 1100,
        four_houses: 1300,
        hotel: 1500,
      }),
      development_cost: JSON.stringify({ house: 200, hotel: 200 }),
    },
    {
      position: 38,
      name: "Luxury Tax",
      type: "tax",
      rent: JSON.stringify({ flat: 75 }),
    },
    {
      position: 39,
      name: "Boardwalk",
      type: "street",
      color: "dark_blue",
      price: 400,
      mortgage_value: 200,
      rent: JSON.stringify({
        site: 50,
        one_house: 200,
        two_houses: 600,
        three_houses: 1400,
        four_houses: 1700,
        hotel: 2000,
      }),
      development_cost: JSON.stringify({ house: 200, hotel: 200 }),
    },
  ]);
};
